name: morin
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  http: ^0.12.0
  flutter_swiper: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  scoped_model: ^1.0.1
  flutter_redux: ^0.5.2
  rxdart: ^0.20.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^3.0.3
  image_picker: ^0.4.10
  shared_preferences: ^0.4.1
  event_bus: ^1.0.1
  cached_network_image: ^0.5.0
  fluro: ^1.3.5
  flutter_i18n: ^0.5.0
  flukit: ^0.0.1
  flutter_candlesticks: ^0.1.2
  web_socket_channel: ^1.0.9
  intro_slider: ^1.0.8
  intro_views_flutter: ^2.4.0
  flutter_screenutil: 0.3.0
  async: '>=1.3.0 <3.0.0'
  crypto: '>=0.9.2 <3.0.0'
  stream_channel: ^1.2.0
  archive: ^2.0.4
  flutter_bloc: ^0.4.11
  video_player: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/i18n/
    - assets/images/intro_page/air-hostess.png
    - assets/images/intro_page/airplane.png
    - assets/images/intro_page/bus-driver.png
    - assets/images/intro_page/bus.png
    - assets/images/intro_page/hotel.png
    - assets/images/intro_page/taxi-driver.png
    - assets/images/intro_page/taxi.png
    - assets/images/intro_page/waiter.png
    - assets/images/ic_file_transfer.png
    - assets/images/ic_fengchao.png
    - assets/images/ic_tx_news.png
    - assets/images/ic_wx_games.png
    - assets/images/ic_new_friend.png
    - assets/images/ic_group_chat.png
    - assets/images/ic_tag.png
    - assets/images/ic_public_account.png
    - assets/images/ic_bottle_msg.png
    - assets/images/ic_feeds.png
    - assets/images/ic_game_entry.png
    - assets/images/ic_mini_program.png
    - assets/images/ic_people_nearby.png
    - assets/images/ic_quick_scan.png
    - assets/images/ic_quick_search.png
    - assets/images/ic_shake_phone.png
    - assets/images/ic_shopping.png
    - assets/images/ic_social_circle.png
    - assets/images/ic_wallet.png
    - assets/images/ic_album.png
    - assets/images/ic_collections.png
    - assets/images/ic_cards_wallet.png
    - assets/images/ic_emotions.png
    - assets/images/ic_settings.png
    - assets/images/ic_qrcode_preview_tiny.png
    - assets/images/default_nor_avatar.png
    - assets/images/img_trade.png
    - assets/images/img_margin.png
    - assets/images/img_fiat.png
    - assets/images/img_helper.png
    - assets/images/icon_notice.png
    - assets/images/home_logo.png
    - assets/images/home_avatar.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: appIconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: MyFont
      fonts:
        - asset: assets/fonts/sspu.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
